apiVersion: v1
kind: Service
metadata:
  name: jirautil
  namespace: prod
  labels:
    app: jirautil
spec:
  ports:
    - port: 8080
  selector:
    app: jirautil
    tier: jirautil
  type: NodePort
