apiVersion: apps/v1beta2  # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jirautil
  namespace: qa
  labels:
    app: jirautil
spec:
  selector:
    matchLabels:
      app: jirautil
      tier: jirautil
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jirautil
        tier: jirautil
    spec:
      containers:
      - image: sarangrana/k8emsprod:2971f79866526062fcdd6689bfde14cfab6a04e778
        name: jirautil
        ports:
        - containerPort: 8080
          name: jirautil
