apiVersion: v1
kind: Service
metadata:
  name: jirautil
  namespace: qa
  labels:
    app: jirautil
spec:
  ports:
    - port: 80
  selector:
    app: jirautil
    tier: jirautil
  type: LoadBalancer
